/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as SearchGalleryRouteImport } from './routes/search.gallery'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as PeopleIdGalleryRouteImport } from './routes/people.$id.gallery'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const SearchGalleryRoute = SearchGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SearchRoute,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const PeopleIdGalleryRoute = PeopleIdGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PeopleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people': typeof PeopleRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/people/$id': typeof PeopleIdRouteWithChildren
  '/photo/$id': typeof PhotoIdRoute
  '/search/gallery': typeof SearchGalleryRoute
  '/people/': typeof PeopleIndexRoute
  '/people/$id/gallery': typeof PeopleIdGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRouteWithChildren
  '/people/$id': typeof PeopleIdRouteWithChildren
  '/photo/$id': typeof PhotoIdRoute
  '/search/gallery': typeof SearchGalleryRoute
  '/people': typeof PeopleIndexRoute
  '/people/$id/gallery': typeof PeopleIdGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people': typeof PeopleRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/people/$id': typeof PeopleIdRouteWithChildren
  '/photo/$id': typeof PhotoIdRoute
  '/search/gallery': typeof SearchGalleryRoute
  '/people/': typeof PeopleIndexRoute
  '/people/$id/gallery': typeof PeopleIdGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/people'
    | '/search'
    | '/people/$id'
    | '/photo/$id'
    | '/search/gallery'
    | '/people/'
    | '/people/$id/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/people/$id'
    | '/photo/$id'
    | '/search/gallery'
    | '/people'
    | '/people/$id/gallery'
  id:
    | '__root__'
    | '/'
    | '/people'
    | '/search'
    | '/people/$id'
    | '/photo/$id'
    | '/search/gallery'
    | '/people/'
    | '/people/$id/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  SearchRoute: typeof SearchRouteWithChildren
  PhotoIdRoute: typeof PhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/search/gallery': {
      id: '/search/gallery'
      path: '/gallery'
      fullPath: '/search/gallery'
      preLoaderRoute: typeof SearchGalleryRouteImport
      parentRoute: typeof SearchRoute
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/$id/gallery': {
      id: '/people/$id/gallery'
      path: '/gallery'
      fullPath: '/people/$id/gallery'
      preLoaderRoute: typeof PeopleIdGalleryRouteImport
      parentRoute: typeof PeopleIdRoute
    }
  }
}

interface PeopleIdRouteChildren {
  PeopleIdGalleryRoute: typeof PeopleIdGalleryRoute
}

const PeopleIdRouteChildren: PeopleIdRouteChildren = {
  PeopleIdGalleryRoute: PeopleIdGalleryRoute,
}

const PeopleIdRouteWithChildren = PeopleIdRoute._addFileChildren(
  PeopleIdRouteChildren,
)

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRouteWithChildren
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRouteWithChildren,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface SearchRouteChildren {
  SearchGalleryRoute: typeof SearchGalleryRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchGalleryRoute: SearchGalleryRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeopleRoute: PeopleRouteWithChildren,
  SearchRoute: SearchRouteWithChildren,
  PhotoIdRoute: PhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
